# Created using wingetcreate 1.0.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: Microsoft.DotNet.Runtime.Preview
PackageVersion: 10.0.0-preview.5.25277.114
MinimumOSVersion: 6.1.7601
InstallerSwitches:
  Silent: /quiet
  SilentWithProgress: /passive
  Custom: /norestart
Installers:
- Architecture: arm64
  InstallerType: burn
  InstallerUrl: https://builds.dotnet.microsoft.com/dotnet/Runtime/10.0.0-preview.5.25277.114/dotnet-runtime-10.0.0-preview.5.25277.114-win-arm64.exe
  InstallerSha256: 0AE0F3B6C7BC2B899DF8D22DEECA658BD3C95AD3BE933B02367700BA95969A15
  ProductCode: '{adcb9585-50ba-48d4-b156-e7be4a6dbd4d}'
  AppsAndFeaturesEntries:
  - DisplayName: Microsoft .NET Runtime - 10.0.0 Preview 5 (arm64)
    Publisher: Microsoft Corporation
    DisplayVersion: 10.0.0.34927
    ProductCode: '{adcb9585-50ba-48d4-b156-e7be4a6dbd4d}'
- Architecture: x64
  InstallerType: burn
  InstallerUrl: https://builds.dotnet.microsoft.com/dotnet/Runtime/10.0.0-preview.5.25277.114/dotnet-runtime-10.0.0-preview.5.25277.114-win-x64.exe
  InstallerSha256: 7F95A5A0AC80A2126E7DCAEB676D25DC6AA8FDC1C45CC1DA6679E1EF6CE53A9E
  ProductCode: '{36abd207-f993-4ffe-b834-03c6fad4b229}'
  AppsAndFeaturesEntries:
  - DisplayName: Microsoft .NET Runtime - 10.0.0 Preview 5 (x64)
    Publisher: Microsoft Corporation
    DisplayVersion: 10.0.0.34927
    ProductCode: '{36abd207-f993-4ffe-b834-03c6fad4b229}'
- Architecture: x86
  InstallerType: burn
  InstallerUrl: https://builds.dotnet.microsoft.com/dotnet/Runtime/10.0.0-preview.5.25277.114/dotnet-runtime-10.0.0-preview.5.25277.114-win-x86.exe
  InstallerSha256: 309FED0AC7F10096ABBF0BA01038B3432BBE3797711D010047834675F3C776AC
  ProductCode: '{80f341ef-a919-4f41-9b34-f4b342bfe930}'
  AppsAndFeaturesEntries:
  - DisplayName: Microsoft .NET Runtime - 10.0.0 Preview 5 (x86)
    Publisher: Microsoft Corporation
    DisplayVersion: 10.0.0.34927
    ProductCode: '{80f341ef-a919-4f41-9b34-f4b342bfe930}'
ManifestType: installer
ManifestVersion: 1.9.0

